FROM node:VERSION

WORKDIR /project

RUN npm i -g npm@latest &&\
    npm i -g \
        express \
        create-react-app \
        @angular/cli \
        vue \
        vue-cli \
        vuex \
        vuese

CMD ["/bin/sh"]
